#!/usr/bin/env python3
"""Create the dev stack's Kafka topics and per-service ACLs (one-shot bootstrap).

WHAT THIS IS FOR
----------------
The broker in ``deployments/docker-compose.dev.yml`` runs with
``authorizer.class.name=kafka.security.authorizer.AclAuthorizer``,
``allow.everyone.if.no.acl.found=false`` and ``auto.create.topics.enable=false``.
Both of those are deliberate -- issue #795 asked for per-service identities and
least-privilege topic ACLs -- but nothing in the repository ever *created* a
topic or an ACL. Every service therefore ran with zero ACLs and every publish
died with ``TOPIC_AUTHORIZATION_FAILED`` (issue #893).

This script is that missing step. It runs as a one-shot ``kafka-init`` compose
service, once the broker reports healthy, and applies:

  * one topic per ``wildframe_events.topics.all_topics()`` entry,
  * one DLQ topic per ``all_dlq_topics()`` entry (the SDK quarantines to
    ``<topic>.dlq`` and a consumer needs write access to it),
  * one ACL per ``(principal, topic, operation)`` triple declared by
    ``_SERVICE_ACL``, which that module documents as "the source of truth for
    Kafka ACLs / RBAC policy",
  * one group ACL per consuming service so ``FindCoordinator`` and
    ``JoinGroup`` are authorised.

WHY IT IS A SEPARATE CONTAINER AND NOT PART OF THE BROKER ENTRYPOINT
--------------------------------------------------------------------
``kafka-acls`` and ``kafka-topics`` are clients: they need a broker that is
already listening. ``deployments/kafka-entrypoint.sh`` runs *before* the broker
launches, so it cannot administer itself, and forking an admin out of it would
make "the ACLs exist" unobservable and racy. A sibling one-shot service with
``depends_on: kafka: condition: service_healthy`` is the ordering this stack
already uses for everything else, and it gives a real exit code:
``service_completed_successfully`` then gates the applications.

It runs inside the existing ``confluentinc/cp-kafka`` image, which already
contains both CLIs and a python3 interpreter -- no new image, no new dependency.

LEAST PRIVILEGE
---------------
The two operation sets were determined empirically against a running 7.5.0
broker rather than assumed:

  * produce needs exactly ``--operation Write`` on the topic: a produce with
    WRITE and nothing else succeeded, so no DESCRIBE is granted;
  * consume needs exactly ``--operation Read`` on the topic plus
    ``--operation Read`` on the consumer group: topic READ without group READ
    fails with ``GroupAuthorizationException``, and READ without WRITE cannot
    produce.

Nothing is granted with a wildcard principal (``User:*``) or a wildcard resource
(``--topic '*'``), and ``--allow-everyone-if-no-acl-found`` is never used. The
only principal that may create anything is the broker's ``admin`` super user,
whose password arrives in ``WF_ADMIN_PASSWORD`` -- the same environment
variable ``deployments/kafka-entrypoint.sh`` uses -- so a real ``.env``
override moves the broker and this bootstrap together.

IDEMPOTENCE
-----------
``kafka-topics --create --if-not-exists`` and ``kafka-acls --add`` both exit 0
when the object already exists (verified against the running broker), so this
is safe to re-run and safe as a ``compose up`` over an existing volume.

Usage:
  python scripts/kafka_init.py              # apply to $KAFKA_BOOTSTRAP_SERVERS
  python scripts/kafka_init.py --print-plan # print the plan; no broker needed
  python scripts/kafka_init.py --help
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import subprocess
import sys
import time
from types import ModuleType
from typing import Dict, List, NamedTuple, Sequence

#: Broker the CLIs talk to. In-network this is the SASL_SSL listener the
#: services use, never the host-facing one.
DEFAULT_BOOTSTRAP = "kafka:29092"

#: The broker's admin super user. deployments/kafka-entrypoint.sh writes
#: ``user_admin="$WF_ADMIN_PASSWORD"`` into the static JAAS section, so the
#: principal name is literally "admin" and only the password varies.
ADMIN_USER = "admin"
ADMIN_PASSWORD_ENV = "WF_ADMIN_PASSWORD"

#: Dev truststore generated by scripts/generate-dev-certs.sh and bind-mounted
#: read-only by the kafka-init compose service.
TRUSTSTORE_PATH = "/etc/kafka/secrets/kafka-truststore.pem"

#: Where the generated client properties land. Deliberately not a committed
#: file: it holds the admin password, so it is written per-run under a 0077
#: umask, exactly as deployments/kafka-entrypoint.sh writes the JAAS file.
CLIENT_PROPERTIES_PATH = "/etc/kafka/kafka-init-client.properties"

#: Where compose bind-mounts packages/sdk/wildframe_events/topics.py.
DEFAULT_TOPICS_REGISTRY = "/opt/wildframe/topics.py"

#: Bounded retry. The broker is already ``service_healthy`` when this runs, so
#: these attempts absorb a broker still settling metadata -- they are not an
#: excuse to paper over a failure. When they are exhausted this script exits
#: non-zero, which fails the compose ``up`` and, because every service waits on
#: ``service_completed_successfully``, stops the applications from starting
#: against a broker they cannot publish to.
MAX_ATTEMPTS = 5
# Overridable because how long a freshly-started broker needs before it will
# accept an admin request is environment-dependent, and a dev laptop and a CI
# runner are not the same machine.
RETRY_DELAY_SECONDS = float(os.environ.get("KAFKA_INIT_RETRY_DELAY_SECONDS", "6"))
#: Hard ceiling on a single kafka CLI invocation. Without it a wedged
#: ``kafka-acls`` blocks this container forever, and because every service waits
#: on ``service_completed_successfully`` that wedges the whole ``compose up``.
#: Observed in practice: the broker answering
#: ``TimeoutException: Timed out waiting for a node assignment`` rather than
#: exiting, because it was being loaded by this script's own sequential launches.
COMMAND_TIMEOUT_SECONDS = float(os.environ.get("KAFKA_INIT_COMMAND_TIMEOUT_SECONDS", "120"))

TOPIC = "topic"
GROUP = "group"
READ = "Read"
WRITE = "Write"


class Acl(NamedTuple):
    """One ``kafka-acls --add`` grant, fully resolved.

    ``principal`` is the SASL username the broker authenticates as, which is
    why it is resolved here rather than assumed to equal the service name.
    """

    principal: str
    operation: str
    resource_type: str
    resource: str

    def render(self) -> str:
        return f"User:{self.principal} {self.operation} {self.resource_type}={self.resource}"


def load_topics_module(path: str) -> ModuleType:
    """Import ``topics.py`` by file path.

    Deliberately not ``import wildframe_events.topics``: the package
    ``__init__`` pulls in ``publisher``/``subscriber`` and therefore aiokafka,
    which is not installed in the cp-kafka image. ``topics.py`` is pure stdlib,
    so loading that one file is enough and keeps this bootstrap dependent on
    nothing but the topic registry itself.
    """
    spec = importlib.util.spec_from_file_location("wildframe_topics_bootstrap", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load the topic registry from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _role_variable(role: str, suffix: str) -> str:
    return f"{role.upper().replace('-', '_')}_{suffix}"


def service_principal(role: str, env: Dict[str, str]) -> str:
    """Return the Kafka SASL username for ``role``.

    Read from ``<ROLE>_KAFKA_USERNAME`` so the bootstrap, the broker's generated
    JAAS file and the services cannot drift: deployments/docker-compose.dev.yml
    gives the kafka and kafka-init services the identical ``${VAR:-default}``
    expression, and deployments/kafka-entrypoint.sh builds the JAAS section from
    the same variable. Falls back to the role name, which is what every compose
    default already is.
    """
    return env.get(_role_variable(role, "KAFKA_USERNAME")) or role


def consumer_group(role: str, env: Dict[str, str]) -> str:
    """Return the consumer group id ``role`` joins.

    Every consumer group in this repository is the service name: the three raw
    ``AIOKafkaConsumer`` call sites hardcode ``CONSUMER_GROUP =
    "<service-name>"`` and ``recommendation-service``'s ``KAFKA_CONSUMER_GROUP``
    default is its own name; compose sets ``KAFKA_GROUP_ID: <service-name>`` for
    all fifteen. Overridable per role via ``<ROLE>_KAFKA_GROUP_ID`` so a rename
    cannot silently leave a consumer with no group ACL, and
    ``tests/test_kafka_init.py`` asserts the code and this derivation agree so
    the default cannot rot unnoticed.
    """
    return env.get(_role_variable(role, "KAFKA_GROUP_ID")) or role


def build_topic_plan(topics_module: ModuleType) -> List[str]:
    """Every topic the stack needs: the canonical set plus one DLQ each.

    A DLQ topic is only ever written by the services, so it needs no grant
    beyond the produce right ``topic_acl(include_dlq=True)`` already hands each
    consumer.
    """
    return sorted(set(topics_module.all_topics()) | set(topics_module.all_dlq_topics()))


def build_acl_plan(topics_module: ModuleType, env: Dict[str, str]) -> "tuple[List[Acl], List[Acl]]":
    """Return ``(topic_acls, group_acls)`` derived from ``_SERVICE_ACL``.

    ``topic_acl(role, include_dlq=True)`` is the registry's own accessor, so
    this walks exactly the matrix the SDK documents as the RBAC source of
    truth. There is deliberately no second, bootstrap-local list that could
    drift from it.
    """
    topic_acls: List[Acl] = []
    # A group ACL is per (principal, group), not per topic, so a service that
    # consumes four topics needs exactly one grant here, not four.
    group_grants: Dict[tuple, Acl] = {}

    for role in sorted(topics_module._SERVICE_ACL):
        principal = service_principal(role, env)
        acl = topics_module.topic_acl(role, include_dlq=True)
        for topic in sorted(set(acl["produce"])):
            topic_acls.append(Acl(principal, WRITE, TOPIC, topic))
        for topic in sorted(set(acl["consume"])):
            topic_acls.append(Acl(principal, READ, TOPIC, topic))
            # A consumer also needs to join and commit on its group. Verified:
            # topic READ without this fails with GroupAuthorizationException.
            group = consumer_group(role, env)
            group_grants[(principal, group)] = Acl(principal, READ, GROUP, group)

    # Sorted so the emitted command list is byte-stable between runs, which is
    # what makes the plan assertable in a test.
    group_acls = [group_grants[key] for key in sorted(group_grants)]
    # Same for topic grants: two roles can name the same topic, and a role that
    # both produces and consumes it gets two distinct operations, so dedupe on
    # the whole tuple rather than on the topic.
    return sorted(set(topic_acls)), group_acls


def render_client_properties(*, admin_user: str, admin_password: str, truststore_path: str) -> str:
    """Build the client config the CLIs authenticate with.

    Mirrors deployments/kafka-client.properties (which the broker healthcheck
    uses) but is generated from the environment instead of committed, because a
    committed copy is a second source of truth for a password and this repo has
    already been bitten by that. No keystore settings: this client presents no
    certificate, and Kafka rejects ``ssl.keystore.password`` outright when the
    truststore type is PEM.
    """
    jaas = (
        "org.apache.kafka.common.security.plain.PlainLoginModule required "
        f'username="{admin_user}" password="{admin_password}";'
    )
    return "\n".join(
        [
            "security.protocol=SASL_SSL",
            "sasl.mechanism=PLAIN",
            f"sasl.jaas.config={jaas}",
            f"ssl.truststore.location={truststore_path}",
            "ssl.truststore.type=PEM",
            # The dev cert carries no SAN for the compose service name "kafka",
            # which is what the broker advertises; the broker disables endpoint
            # identification to match.
            "ssl.endpoint.identification.algorithm=",
            "",
        ]
    )


def write_client_properties(path: str, contents: str) -> None:
    """Write the client config owner-only: it contains the admin password."""
    previous_umask = os.umask(0o077)
    try:
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(contents)
    finally:
        os.umask(previous_umask)


def topic_command(binary: str, bootstrap: str, config: str, topic: str) -> List[str]:
    return [
        binary,
        "--bootstrap-server",
        bootstrap,
        "--command-config",
        config,
        "--create",
        "--if-not-exists",
        "--topic",
        topic,
        "--partitions",
        "1",
        "--replication-factor",
        "1",
    ]


def acl_command(binary: str, bootstrap: str, config: str, acl: Acl) -> List[str]:
    command = [
        binary,
        "--bootstrap-server",
        bootstrap,
        "--command-config",
        config,
        "--add",
        "--allow-principal",
        f"User:{acl.principal}",
        "--operation",
        acl.operation,
    ]
    if acl.resource_type == GROUP:
        command += ["--group", acl.resource]
    else:
        command += ["--topic", acl.resource]
    return command


def plan_commands(
    topics: Sequence[str],
    topic_acls: Sequence[Acl],
    group_acls: Sequence[Acl],
    *,
    bootstrap: str,
    config: str,
    topics_binary: str = "kafka-topics",
    acls_binary: str = "kafka-acls",
) -> List[List[str]]:
    """Render the whole plan as argv lists, in apply order.

    Pure -- no I/O -- so a test can read exactly what this would execute.
    """
    commands = [topic_command(topics_binary, bootstrap, config, topic) for topic in topics]
    commands += [
        acl_command(acls_binary, bootstrap, config, acl)
        for acl in list(topic_acls) + list(group_acls)
    ]
    return commands


def describe_plan(
    topics: Sequence[str], topic_acls: Sequence[Acl], group_acls: Sequence[Acl]
) -> str:
    lines = [f"# {len(topics)} topics", *topics]
    lines.append(f"# {len(topic_acls)} topic ACLs")
    lines += [acl.render() for acl in topic_acls]
    lines.append(f"# {len(group_acls)} consumer-group ACLs")
    lines += [acl.render() for acl in group_acls]
    return "\n".join(lines)


def run(command: Sequence[str]) -> None:
    """Run one CLI, echoing it and surfacing any failure."""
    print("$ " + " ".join(command), flush=True)
    try:
        completed = subprocess.run(
            list(command),
            capture_output=True,
            text=True,
            check=False,
            timeout=COMMAND_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired as exc:
        # Surfaced as RuntimeError so the bounded retry in apply_plan handles a
        # hung CLI the same way it handles a failing one, rather than hanging
        # the container and every service that waits on it.
        raise RuntimeError(
            f"{command[0]} did not finish within {COMMAND_TIMEOUT_SECONDS:g}s"
        ) from exc
    if completed.stdout.strip():
        print(completed.stdout.strip(), flush=True)
    if completed.returncode != 0:
        # Raised, never swallowed: apply_plan retries a bounded number of times
        # and then main() exits non-zero.
        raise RuntimeError(
            f"{command[0]} exited {completed.returncode}: "
            f"{(completed.stderr or completed.stdout).strip()}"
        )


def apply_plan(commands: Sequence[Sequence[str]], *, max_attempts: int) -> None:
    # Resume from the failure rather than restarting the plan.
    #
    # Both command kinds are idempotent -- kafka-topics --create and
    # kafka-acls --add can be re-applied -- so restarting from zero is pure
    # waste. It is also actively harmful: this plan is ~190 sequential JVM
    # launches, and re-running all of them after a failure near the end loads
    # the single broker harder, which is the very condition that caused the
    # failure. Observed on a re-run: 461 commands issued where 190 were
    # planned, ending in a TimeoutException retry loop.
    start = 0
    for attempt in range(1, max_attempts + 1):
        try:
            for index in range(start, len(commands)):
                run(commands[index])
                start = index + 1
        except RuntimeError as exc:
            print(
                f"attempt {attempt}/{max_attempts} failed at command {start + 1}: {exc}",
                file=sys.stderr,
                flush=True,
            )
            if attempt == max_attempts:
                raise
            time.sleep(RETRY_DELAY_SECONDS)
        else:
            print(
                f"applied {len(commands)} commands on attempt {attempt}",
                flush=True,
            )
            return


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create the dev stack's Kafka topics and per-service ACLs. Runs as "
            "the kafka-init compose service; --print-plan needs no broker."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--bootstrap",
        default=os.environ.get("KAFKA_BOOTSTRAP_SERVERS", DEFAULT_BOOTSTRAP),
        help=("broker to talk to (default: $KAFKA_BOOTSTRAP_SERVERS or " f"{DEFAULT_BOOTSTRAP})"),
    )
    parser.add_argument(
        "--client-config",
        default=CLIENT_PROPERTIES_PATH,
        help=(
            "where to write the generated client properties " f"(default: {CLIENT_PROPERTIES_PATH})"
        ),
    )
    parser.add_argument(
        "--topics-registry",
        default=DEFAULT_TOPICS_REGISTRY,
        help=("path to wildframe_events/topics.py " f"(default: {DEFAULT_TOPICS_REGISTRY})"),
    )
    parser.add_argument(
        "--print-plan",
        action="store_true",
        help="print the topic and ACL plan and exit without contacting the broker",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str]) -> int:
    args = parse_args(argv)

    topics_module = load_topics_module(args.topics_registry)
    topics = build_topic_plan(topics_module)
    topic_acls, group_acls = build_acl_plan(topics_module, dict(os.environ))

    if args.print_plan:
        print(describe_plan(topics, topic_acls, group_acls))
        return 0

    admin_password = os.environ.get(ADMIN_PASSWORD_ENV)
    if not admin_password:
        # Loud, with no default: a broker holding an empty admin password can
        # never authenticate anybody, and a silent default would present as a
        # broker fault instead of a missing environment variable.
        print(
            "Required admin credentials are missing; cannot authenticate as "
            "the configured super user",
            file=sys.stderr,
        )
        return 2

    write_client_properties(
        args.client_config,
        render_client_properties(
            admin_user=ADMIN_USER,
            admin_password=admin_password,
            truststore_path=TRUSTSTORE_PATH,
        ),
    )
    print(f"wrote {args.client_config} (mode 0600)", flush=True)

    commands = plan_commands(
        topics,
        topic_acls,
        group_acls,
        bootstrap=args.bootstrap,
        config=args.client_config,
    )
    try:
        apply_plan(commands, max_attempts=MAX_ATTEMPTS)
    except RuntimeError as exc:
        print(f"kafka bootstrap failed: {exc}", file=sys.stderr)
        return 1
    finally:
        try:
            if os.path.exists(args.client_config):
                os.remove(args.client_config)
        except OSError as cleanup_exc:
            print(
                f"warning: failed to remove {args.client_config}: {cleanup_exc}",
                file=sys.stderr,
            )
    print(
        f"kafka bootstrap complete: {len(topics)} topics, "
        f"{len(topic_acls)} topic ACLs, {len(group_acls)} group ACLs",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
